# Generated by Django 5.0.6 on 2024-10-16 20:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "cpf",
                    models.CharField(
                        error_messages={"unique": "Cpf já cadastrado."},
                        max_length=11,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(blank=True, max_length=100, null=True)),
                ("apelido", models.CharField(blank=True, max_length=50, null=True)),
                ("documento", models.CharField(blank=True, max_length=20, null=True)),
                ("cnpj", models.CharField(blank=True, max_length=14, null=True)),
                ("telefone", models.CharField(blank=True, max_length=11, null=True)),
                ("telefone2", models.CharField(blank=True, max_length=11, null=True)),
                ("endereco", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "numero_endereco",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("cep", models.CharField(blank=True, max_length=8, null=True)),
                ("bairro", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "complemento",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("uf", models.CharField(blank=True, max_length=2, null=True)),
                ("cidade", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("bloqueado", models.BooleanField(default=False)),
                ("data_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "vinculo_telefone2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "status_relatorio",
                    models.CharField(
                        choices=[
                            ("NV", "Novo"),
                            ("R", "Renovado"),
                            ("NG", "Negociado"),
                            ("AC", "Finalizado"),
                        ],
                        default="Outro",
                        max_length=10,
                    ),
                ),
                (
                    "grupo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.group",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ComprovantePIX",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arquivo", models.ImageField(upload_to="comprovantes_pix/")),
                (
                    "identificador",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("data_upload", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Emprestimo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("capital", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "capital_inicial",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "capital_adicional_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("taxa_juros", models.DecimalField(decimal_places=2, max_digits=5)),
                ("data_inicio", models.DateField()),
                ("data_vencimento", models.DateField()),
                (
                    "total_recebido",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_recebido_dinheiro",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "frequencia",
                    models.CharField(
                        choices=[
                            ("diaria", "Diária"),
                            ("semanal", "Semanal"),
                            ("quinzenal", "Quinzenal"),
                            ("mensal", "Mensal"),
                        ],
                        default="mensal",
                        max_length=10,
                    ),
                ),
                ("numero_parcelas", models.IntegerField(default=12)),
                (
                    "valor_parcelado",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "valor_total_calculado",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("renovado", models.BooleanField(default=False)),
                (
                    "saldo_devedor",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("data_renovacao", models.DateTimeField(blank=True, null=True)),
                (
                    "capital_adicional",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "juros_recebidos",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "total_juros_recebidos",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "dias_semana",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativo", "Ativo"),
                            ("R", "Renovado"),
                            ("NG", "Negociado"),
                            ("finalizado", "Finalizado"),
                            ("inadimplentes", "Inadimplentes"),
                        ],
                        default="ativo",
                        max_length=20,
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PELFCRED.cliente",
                    ),
                ),
                (
                    "grupo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.group",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pagamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_pagamento", models.DateTimeField()),
                (
                    "valor_pago",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "tipo_pagamento",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pix", "PIX"),
                            ("dinheiro", "Dinheiro"),
                            ("banco_outro", "Banco de Outra Pessoa"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("cpf_pagador", models.CharField(blank=True, max_length=11, null=True)),
                (
                    "nome_pagador",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "comprovante_pix",
                    models.ImageField(
                        blank=True, null=True, upload_to="comprovantes_pix/"
                    ),
                ),
                (
                    "emprestimo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagamentos",
                        to="PELFCRED.emprestimo",
                    ),
                ),
                (
                    "grupo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.group",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Parcela",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_vencimento", models.DateField()),
                ("pago", models.BooleanField(default=False)),
                ("data_pagamento", models.DateField(blank=True, null=True)),
                (
                    "emprestimo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parcelas_emprestimo",
                        to="PELFCRED.emprestimo",
                    ),
                ),
            ],
        ),
    ]
