# Generated by Django 5.0.6 on 2024-10-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PELFCRED", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emprestimo",
            name="status",
            field=models.CharField(
                choices=[
                    ("ativo", "Ativo"),
                    ("R", "R"),
                    ("NG", "Negociado"),
                    ("finalizado", "Finalizado"),
                    ("inadimplentes", "Inadimplentes"),
                ],
                default="ativo",
                max_length=20,
            ),
        ),
    ]
