# Generated by Django 5.0.6 on 2024-09-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PELFCRED", "0002_rename_pais_cliente_bairro_remove_cliente_ddd_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="cep",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
