# Generated by Django 5.0.6 on 2024-10-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PELFCRED", "0002_alter_emprestimo_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emprestimo",
            name="status",
            field=models.CharField(
                choices=[
                    ("ativo", "Ativo"),
                    ("R", "R"),
                    ("NG", "NG"),
                    ("finalizado", "AC"),
                    ("inadimplentes", "Inadimplente"),
                ],
                default="ativo",
                max_length=20,
            ),
        ),
    ]
