# Generated by Django 5.0.6 on 2024-10-04 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PELFCRED", "0003_alter_cliente_cep"),
    ]

    operations = [
        migrations.AddField(
            model_name="emprestimo",
            name="total_recebido",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="emprestimo",
            name="total_recebido_dinheiro",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
