# Generated by Django 5.0.6 on 2024-10-20 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PELFCRED", "0003_alter_emprestimo_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="emprestimo",
            name="status_anterior",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
