# Generated by Django 5.0.6 on 2024-10-07 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PELFCRED", "0004_emprestimo_total_recebido_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emprestimo",
            name="status",
            field=models.CharField(
                choices=[
                    ("ativo", "Ativo"),
                    ("renovado", "Renovado"),
                    ("finalizado", "Finalizado"),
                ],
                default="ativo",
                max_length=20,
            ),
        ),
    ]
