# Generated by Django 5.0.6 on 2024-10-26 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PELFCRED", "0005_saida"),
    ]

    operations = [
        migrations.CreateModel(
            name="JurosRecebido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data_hora", models.DateTimeField(auto_now_add=True)),
                (
                    "emprestimo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jurosrecebidos_set",
                        to="PELFCRED.emprestimo",
                    ),
                ),
            ],
        ),
    ]
