# Generated by Django 5.0.6 on 2024-10-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PELFCRED", "0005_emprestimo_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emprestimo",
            name="status",
            field=models.CharField(
                choices=[
                    ("ativo", "Ativo"),
                    ("renovado", "Renovado"),
                    ("finalizado", "Finalizado"),
                    ("inadimplentes", "Inadimplentes"),
                ],
                default="ativo",
                max_length=20,
            ),
        ),
    ]
