# Generated by Django 5.0.6 on 2024-10-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PELFCRED", "0006_jurosrecebido"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emprestimo",
            name="data_inicio",
            field=models.DateTimeField(),
        ),
    ]
