# Generated by Django 5.0.6 on 2024-10-10 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PELFCRED", "0006_alter_emprestimo_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="status_relatorio",
            field=models.CharField(
                choices=[("NV", "Novo"), ("Outro", "Outro")],
                default="Outro",
                max_length=10,
            ),
        ),
    ]
