# Generated by Django 5.0.6 on 2024-10-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PELFCRED", "0007_cliente_status_relatorio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="status_relatorio",
            field=models.CharField(
                choices=[
                    ("NV", "Novo"),
                    ("R", "Renovado"),
                    ("NG", "Negociado"),
                    ("AC", "Finalizado"),
                ],
                default="Outro",
                max_length=10,
            ),
        ),
    ]
