# Generated by Django 5.0.6 on 2024-10-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PELFCRED", "0007_alter_emprestimo_data_inicio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emprestimo",
            name="data_inicio",
            field=models.DateField(),
        ),
    ]
