# Generated by Django 5.0.6 on 2024-10-16 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PELFCRED", "0008_alter_cliente_status_relatorio"),
    ]

    operations = [
        migrations.AddField(
            model_name="emprestimo",
            name="capital_inicial",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
