# Generated by Django 5.0.6 on 2024-10-26 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PELFCRED", "0008_alter_emprestimo_data_inicio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jurosrecebido",
            name="emprestimo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="total_lucro_recebido",
                to="PELFCRED.emprestimo",
            ),
        ),
    ]
