# Generated by Django 5.0.6 on 2024-10-16 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PELFCRED", "0009_emprestimo_capital_inicial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emprestimo",
            name="capital_adicional_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
