# Generated by Django 5.0.6 on 2024-10-26 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PELFCRED", "0009_alter_jurosrecebido_emprestimo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jurosrecebido",
            name="emprestimo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jurosrecebidos",
                to="PELFCRED.emprestimo",
            ),
        ),
    ]
