# Generated by Django 5.0.6 on 2024-11-12 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PELFCRED", "0012_descontojuros_data_fim_descontojuros_data_inicio"),
    ]

    operations = [
        migrations.AddField(
            model_name="saida",
            name="descricao",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
