# Generated by Django 5.0.6 on 2024-11-12 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("PELFCRED", "0013_saida_descricao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="saida",
            name="descricao",
        ),
    ]
